server:
  servlet:
    context-path: /api/v1
spring:
  data:
    redis:
      host: redis
      port: 6379
  application:
    name: fileprocessing
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
upload:
  allowed-content-types:
    - "image/jpg"
    - "image/png"
    - "image/jpeg"
scan:
  scan-url: https://www.virustotal.com/api/v3/files
  api-key: ${SCAN_API_KEY}
jwt:
  secret: ${JWT_SECRET}
