server:
  servlet:
    context-path: /api/v1
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-group-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  application:
    name: fileprocessing
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
checksum:
  algorithm: "SHA-256"
upload:
  allowed-content-types:
    - "image/jpg"
    - "image/png"
    - "image/jpeg"
storage:
  path: "uploads"